sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9.2'

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm prune
- npm update

script: mocha

notifications:
  email:
    on_success: change
    on_failure: always
